import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

const BASE_WIDTH = 10.8;
const BASE_HEIGHT = 19.2;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  navigationBar: {
    position: 'relative',
    width: wp(1080 / BASE_WIDTH),
    height: hp(215 / BASE_HEIGHT),
    backgroundColor: '#3D447B',
  },
  navigationContainer: {
    position: 'absolute',
    width: wp(920 / BASE_WIDTH),
    height: hp(112 / BASE_HEIGHT),
    bottom: 0,
    left: wp(80 / BASE_WIDTH),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconContainer: {
    position: 'relative',
    width: wp(141 / BASE_WIDTH),
    // top: hp(108 / BASE_HEIGHT),
    height: hp(112 / BASE_HEIGHT),
    // left: wp(70 / BASE_WIDTH),
    // zIndex: 100,
  },
  content: {
    // position: 'absolute',
    position: 'relative',
    flexDirection: 'row',
    // width: '60%',
    alignItems: 'center',
    justifyContent: 'center',
    top: hp(0 / BASE_HEIGHT),
    height: hp(100 / BASE_HEIGHT),
    // left: '20%',
    // backgroundColor: 'pink',
  },
  contentText: {
    color: '#fff',
    textAlign: 'center',
    fontSize: hp(48 / BASE_HEIGHT),
    fontWeight: 'bold',
    height: hp(100 / BASE_HEIGHT),
    lineHeight: hp(100 / BASE_HEIGHT),
  },
  iconContainerRight: {
    // position: 'absolute',
    position: 'relative',
    width: wp(61 / BASE_WIDTH),
    // marginTop: hp(19 / BASE_HEIGHT),
    height: hp(112 / BASE_HEIGHT),
    // right: wp(60 / BASE_WIDTH),
    // zIndex: 100,
  },
  changePic: {
    position: 'absolute',
    top: 0,
    right: 0,
    marginTop: hp(25 / BASE_HEIGHT),
    width: wp(62 / BASE_WIDTH),
    height: wp(62 / BASE_WIDTH),
  },
  rect: {
    position: 'absolute',
    width: wp(141 / BASE_WIDTH),
    height: hp(72 / BASE_HEIGHT),
    marginTop: hp(20 / BASE_HEIGHT),
  },
  leftText: {
    color: '#fff',
    width: wp(141 / BASE_WIDTH),
    height: hp(72 / BASE_HEIGHT),
    marginTop: hp(20 / BASE_HEIGHT),
    lineHeight: hp(72 / BASE_HEIGHT),
    textAlign: 'center',
    fontSize: hp(32 / BASE_HEIGHT),
    fontWeight: 'bold',
  },
  actionSheet: {
    position: 'absolute',
    zIndex: 999,
    top: hp(215 / BASE_HEIGHT),
    left: hp(0 / BASE_HEIGHT),
    width: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    height: '100%',
  },
  storeTypeContainer: {
    position: 'relative',
    width: '100%',
    flexWrap: 'wrap',
    height: 'auto',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    backgroundColor: '#fff',
  },
  leftBtnContainer: {
    width: wp(185 / BASE_WIDTH),
    height: 'auto',
    justifyContent: 'flex-start',
    alignContent: 'center',
    paddingLeft: wp(15 / BASE_WIDTH),
    borderRightWidth: 1,
    borderColor: '#ccc',
  },
  ScrollView: {
    position: 'relative',
    width: 'auto',
    height: hp(400 / BASE_HEIGHT),
  },
  leftBtn: {
    width: wp(160 / BASE_WIDTH),
    height: hp(100 / BASE_HEIGHT),
    backgroundColor: '#fff',
    borderColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 0,
    padding: 0,
  },
  leftBtnText: {
    marginLeft: wp(20 / BASE_WIDTH),
    width: wp(300 / BASE_WIDTH),
    color: '#333',
    height: hp(100 / BASE_HEIGHT),
    lineHeight: hp(100 / BASE_HEIGHT),
    textAlign: 'left',
    fontSize: hp(32 / BASE_HEIGHT),
    fontWeight: 'bold',
  },
  typeBottom: {
    height: '100%',
    width: wp(100),
  },
  leftBtnTextActive: {
    marginLeft: wp(20 / BASE_WIDTH),
    width: wp(300 / BASE_WIDTH),
    color: '#3D447B',
    height: hp(100 / BASE_HEIGHT),
    lineHeight: hp(100 / BASE_HEIGHT),
    textAlign: 'left',
    fontSize: hp(32 / BASE_HEIGHT),
    fontWeight: 'bold',
  },
  leftBtnTextActive1: {
    width: wp(160 / BASE_WIDTH),
    color: '#3D447B',
    height: hp(100 / BASE_HEIGHT),
    lineHeight: hp(100 / BASE_HEIGHT),
    textAlign: 'center',
    fontSize: hp(32 / BASE_HEIGHT),
    fontWeight: 'bold',
  },
  leftBtnText1: {
    width: wp(160 / BASE_WIDTH),
    color: '#333',
    height: hp(100 / BASE_HEIGHT),
    lineHeight: hp(100 / BASE_HEIGHT),
    textAlign: 'center',
    fontSize: hp(32 / BASE_HEIGHT),
    fontWeight: 'bold',
  },
  rightBtn: {
    width: wp(880 / BASE_WIDTH),
    height: hp(100 / BASE_HEIGHT),
    backgroundColor: '#fff',
    borderColor: '#fff',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingVertical: 0,
  },
  tabContainer: {},
  commonBtn: {
    position: 'relative',
    width: wp(250 / BASE_WIDTH),
    height: hp(76 / BASE_HEIGHT),
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  commonBtn2: {
    position: 'relative',
    width: wp(250 / BASE_WIDTH),
    height: hp(76 / BASE_HEIGHT),
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: wp(1 / BASE_WIDTH),
    borderRightColor: '#C0C1C2',
  },
  commonText: {
    color: '#3D447B',
    width: wp(250 / BASE_WIDTH),
    height: hp(60 / BASE_HEIGHT),
    lineHeight: hp(60 / BASE_HEIGHT),
    textAlign: 'center',
    fontSize: hp(32 / BASE_HEIGHT),
    fontWeight: 'bold',
  },
  commonrowText: {
    color: '#333',
    width: wp(240 / BASE_WIDTH),
    height: hp(80 / BASE_HEIGHT),
    lineHeight: hp(80 / BASE_HEIGHT),
    textAlign: 'center',
    fontSize: hp(20 / BASE_HEIGHT),
    fontWeight: 'bold',
  },
  commonBorder: {
    position: 'absolute',
    bottom: hp(12 / BASE_HEIGHT),
    width: wp(150 / BASE_WIDTH),
    height: hp(4 / BASE_HEIGHT),
    backgroundColor: '#3D447B',
  },
  centerContainer: {
    position: 'relative',
    width: wp(996 / BASE_WIDTH),
    height: hp(946 / BASE_HEIGHT),
    // backgroundColor: '#fff',
    marginLeft: wp(42 / BASE_WIDTH),
    marginTop: hp(33 / BASE_HEIGHT),
    // borderTopLeftRadius: 0,
    // borderTopRightRadius: 0,
    // borderBottomLeftRadius: wp(20 / BASE_WIDTH),
    // borderBottomRightRadius: wp(20 / BASE_WIDTH),
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 2, height: 2 },
    elevation: 1,
  },
  tableContainer: {
    position: 'relative',
    width: wp(960 / BASE_WIDTH),
    height: 'auto',
    backgroundColor: '#fff',
    // marginLeft: wp(40 / BASE_WIDTH),
    marginTop: hp(33 / BASE_HEIGHT),
  },
  commonTableContainer: {
    position: 'relative',
    width: wp(960 / BASE_WIDTH),
    marginLeft: wp(90 / BASE_WIDTH),
    // backgroundColor: 'pink',
  },
  tabTitleContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: hp(47 / BASE_HEIGHT),
  },
  shuPic: {
    width: wp(10 / BASE_WIDTH),
    height: hp(40 / BASE_HEIGHT),
    marginRight: wp(10 / BASE_WIDTH),
  },
  tabTitle: {
    color: '#3D447B',
    textAlign: 'center',
    fontSize: hp(32 / BASE_HEIGHT),
    fontWeight: 'bold',
  },
  headContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  nameStyle: {
    height: 'auto',
    width: wp(960 / 4 / BASE_WIDTH),
  },
  commonColText: {
    color: '#6972CC',
    textAlign: 'center',
    fontSize: hp(24 / BASE_HEIGHT),
    fontWeight: 'bold',
  },
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#fff',
    flexWrap: 'wrap',
  },
});
