import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

const BASE_WIDTH = 10.8;
const BASE_HEIGHT = 19.2;

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  navigationBar: {
    width: wp(1080 / BASE_WIDTH),
    height: hp(215 / BASE_HEIGHT),
    backgroundColor: '#3D447B',
  },
  iconContainer: {
    position: 'absolute',
    width: 'auto',
    top: hp(130 / BASE_HEIGHT),
    height: hp(215 / BASE_HEIGHT),
    left: wp(70 / BASE_WIDTH),
    zIndex: 100,
  },
  content: {
    position: 'absolute',
    color: '#fff',
    width: '100%',
    textAlign: 'center',
    fontSize: hp(48 / BASE_HEIGHT),
    fontWeight: 'bold',
    top: hp(128 / BASE_HEIGHT),
    height: hp(215 / BASE_HEIGHT),
    // left: wp(70 / BASE_WIDTH),
  },
  conditionContainer: {
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: hp(44 / BASE_HEIGHT),
    width: wp(976 / BASE_WIDTH),
    // backgroundColor: 'pink',
    marginLeft: wp(52 / BASE_WIDTH),
  },
  levelContainer: {
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: wp(264 / BASE_WIDTH),
    height: hp(82 / BASE_HEIGHT),
    backgroundColor: '#fff',
    // marginLeft: wp(52 / BASE_WIDTH),
    borderRadius: wp(10 / BASE_WIDTH),
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: {
      width: 10,
      height: 10,
    },
    elevation: 1.5,
  },
  statusContainer: {
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: wp(570 / BASE_WIDTH),
    height: hp(82 / BASE_HEIGHT),
    backgroundColor: '#fff',
    marginLeft: wp(30 / BASE_WIDTH),
    borderRadius: wp(10 / BASE_WIDTH),
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: {
      width: 10,
      height: 10,
    },
    elevation: 1.5,
  },
  orderContainer: {
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: wp(106 / BASE_WIDTH),
    height: hp(82 / BASE_HEIGHT),
    backgroundColor: '#fff',
    marginLeft: wp(30 / BASE_WIDTH),
    borderRadius: wp(10 / BASE_WIDTH),
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 10, height: 10 },
  },
  card: {
    alignItems: 'center',
    width: wp(260 / BASE_WIDTH),
    height: hp(350 / BASE_HEIGHT),
    marginBottom: hp(40 / BASE_HEIGHT),
    marginRight: wp(66 / BASE_WIDTH),
    backgroundColor: '#fff',
    borderRadius: wp(15 / BASE_WIDTH),
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 10, height: 10 },
  },
  commonText: {
    textAlign: 'left',
    color: '#3D447B',
    fontWeight: 'normal',
    // marginLeft: wp(40 / BASE_WIDTH),
    fontSize: hp(32 / BASE_HEIGHT),
    lineHeight: hp(82 / BASE_HEIGHT),
  },
  commonText2: {
    width: '60%',
    textAlign: 'left',
    color: '#3D447B',
    fontWeight: 'normal',
    marginLeft: wp(40 / BASE_WIDTH),
    fontSize: hp(32 / BASE_HEIGHT),
    lineHeight: hp(82 / BASE_HEIGHT),
  },
  arrowPic: {
    position: 'absolute',
    top: hp(35 / BASE_HEIGHT),
    right: wp(28 / BASE_WIDTH),
    width: wp(20 / BASE_WIDTH),
    height: hp(12 / BASE_HEIGHT),
    // marginLeft: wp(30 / BASE_WIDTH),
  },
  orderPic: {
    width: wp(48 / BASE_WIDTH),
    height: wp(48 / BASE_WIDTH),
  },
  inputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: wp(866 / BASE_WIDTH),
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 1, height: 1 },
    borderColor: '#ccc',
    borderWidth: 1,
    shadowOpacity: 0.9,
    height: hp(80 / BASE_HEIGHT),
    borderRadius: wp(40 / BASE_WIDTH),
    marginLeft: wp(92 / BASE_WIDTH),
    marginTop: hp(30 / BASE_HEIGHT),
  },
  inputBase: {
    color: '#333',
    width: '90%',
    paddingVertical: 0,
    textAlign: 'center',
    fontSize: hp(32 / BASE_HEIGHT),
    paddingLeft: wp(10 / BASE_WIDTH),
    lineHeight: hp((32 * 1.2) / BASE_HEIGHT),
  },
  searchIcon: {
    width: wp(33 / BASE_WIDTH),
    height: wp(33 / BASE_WIDTH),
  },
  warningContent: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    width: wp(866 / BASE_WIDTH),
    marginLeft: wp(127 / BASE_WIDTH),
    height: 'auto',
    marginTop: hp(36 / BASE_HEIGHT),
    marginBottom: hp(28 / BASE_HEIGHT),
  },
  ScrollView: {
    width: 'auto',
    height: 'auto',
    marginLeft: wp(40 / BASE_WIDTH),
  },
  warningText: {
    color: '#888',
    textAlign: 'left',
    fontSize: hp(28 / BASE_HEIGHT),
    lineHeight: hp(36 / BASE_HEIGHT),
  },
  redText: {
    color: '#F70404',
    fontSize: hp(28 / BASE_HEIGHT),
    lineHeight: hp(36 / BASE_HEIGHT),
  },
  commonContainer: {
    position: 'relative',
    width: wp(984 / BASE_WIDTH),
    // height: hp(292 / BASE_HEIGHT),
    marginLeft: wp(36 / BASE_WIDTH),
    marginBottom: hp(35 / BASE_HEIGHT),
    // backgroundColor: 'pink',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    borderRadius: wp(20 / BASE_WIDTH),
  },
  leftPart: {
    marginRight: wp(17 / BASE_WIDTH),
  },
  rightPart: {
    width: wp(868 / BASE_WIDTH),
    height: 'auto',
    paddingTop: hp(52 / BASE_HEIGHT),
    paddingBottom: hp(52 / BASE_HEIGHT),
    backgroundColor: '#fff',
  },
  commonPic: {
    width: wp(72 / BASE_WIDTH),
    height: wp(72 / BASE_WIDTH),
    marginRight: wp(17 / BASE_WIDTH),
  },
  commonLine: {
    color: '#999',
    width: wp(780 / BASE_WIDTH),
    marginLeft: wp(48 / BASE_WIDTH),
    fontSize: hp(28 / BASE_HEIGHT),
    lineHeight: hp(36 / BASE_HEIGHT),
    marginBottom: hp(8 / BASE_HEIGHT),
  },
  contents: {
    color: '#F70404',
    fontSize: hp(28 / BASE_HEIGHT),
    lineHeight: hp(36 / BASE_HEIGHT),
  },
  arrow: {
    position: 'absolute',
    zIndex: 100,
    top: hp(24 / BASE_HEIGHT),
    left: wp(74 / BASE_WIDTH),
    marginBottom: wp(5 / BASE_WIDTH),
    marginTop: hp(1 / BASE_HEIGHT),
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderWidth: wp(16 / BASE_WIDTH),
    borderTopColor: 'transparent', //下箭头颜色
    borderLeftColor: 'transparent', //右箭头颜色
    borderBottomColor: 'transparent', //上箭头颜色
    borderRightColor: '#fff', //左箭头颜色
  },
  confirmBtn: {
    width: 'auto',
    position: 'absolute',
    top: hp(44 / BASE_HEIGHT),
    right: wp(32 / BASE_WIDTH),
    borderColor: '#fff',
    backgroundColor: '#fff',
    paddingVertical: 0,
    padding: 0,
    height: hp(64 / BASE_HEIGHT),
    borderRadius: wp(10 / BASE_WIDTH),
  },
  isConfirm: {
    width: 'auto',
    position: 'absolute',
    top: hp(44 / BASE_HEIGHT),
    right: wp(32 / BASE_WIDTH),
    borderColor: '#B9B9B9',
    backgroundColor: '#B9B9B9',
    paddingVertical: 0,
    height: hp(64 / BASE_HEIGHT),
    borderRadius: wp(10 / BASE_WIDTH),
  },
  confirmBtnText: {
    width: '100%',
    paddingHorizontal: 0,
    color: '#000',
    textAlign: 'center',
    fontSize: hp(24 / BASE_HEIGHT),
    lineHeight: hp(36 / BASE_HEIGHT),
  },
  loadMoreView: {
    alignItems: 'center',
    paddingTop: hp(2),
    paddingBottom: hp(2),
  },
  loadMoreText: {
    color: '#333',
    fontSize: hp(24 / BASE_HEIGHT),
    lineHeight: hp(36 / BASE_HEIGHT),
  },
  emptyText: {
    color: '#333',
    fontSize: hp(24 / BASE_HEIGHT),
    lineHeight: hp(36 / BASE_HEIGHT),
  },
  noDataView: {
    flex: 1,
    alignItems: 'center',
    paddingTop: hp(2),
    paddingBottom: hp(2),
    justifyContent: 'center',
  },
  noRelust: {
    color: '#333',
    fontSize: hp(24 / BASE_HEIGHT),
    lineHeight: hp(36 / BASE_HEIGHT),
  },
  dashItem: {
    height: hp(1 / BASE_HEIGHT),
    width: wp(1 / BASE_WIDTH),
    marginTop: hp(10 / BASE_HEIGHT),
    flex: 1,
  },
});
