import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

const BASE_WIDTH = 10.8;
const BASE_HEIGHT = 19.2;

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  navigationBar: {
    width: wp(1080 / BASE_WIDTH),
    height: wp(215 / BASE_WIDTH),
    backgroundColor: '#3D447B',
  },
  iconContainer: {
    position: 'absolute',
    width: 'auto',
    top: hp(130 / BASE_HEIGHT),
    height: hp(215 / BASE_HEIGHT),
    left: wp(70 / BASE_WIDTH),
    zIndex: 100,
  },
  content: {
    position: 'absolute',
    color: '#fff',
    width: '100%',
    textAlign: 'center',
    fontSize: hp(48 / BASE_HEIGHT),
    fontWeight: 'bold',
    top: hp(128 / BASE_HEIGHT),
    height: hp(215 / BASE_HEIGHT),
    // left: wp(70 / BASE_WIDTH),
  },
  conditionContainer: {
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: hp(44 / BASE_HEIGHT),
  },
  levelContainer: {
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: wp(264 / BASE_WIDTH),
    height: hp(82 / BASE_HEIGHT),
    backgroundColor: '#fff',
    marginLeft: wp(53 / BASE_WIDTH),
    borderRadius: wp(10 / BASE_WIDTH),
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 10, height: 10 },
  },
  statusContainer: {
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: wp(264 / BASE_WIDTH),
    height: hp(82 / BASE_HEIGHT),
    backgroundColor: '#fff',
    marginLeft: wp(30 / BASE_WIDTH),
    borderRadius: wp(10 / BASE_WIDTH),
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 10, height: 10 },
  },
  orderContainer: {
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: wp(106 / BASE_WIDTH),
    height: hp(82 / BASE_HEIGHT),
    backgroundColor: '#fff',
    marginLeft: wp(30 / BASE_WIDTH),
    borderRadius: wp(10 / BASE_WIDTH),
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 10, height: 10 },
  },
  card: {
    alignItems: 'center',
    width: wp(260 / BASE_WIDTH),
    height: hp(350 / BASE_HEIGHT),
    marginBottom: hp(40 / BASE_HEIGHT),
    marginRight: wp(66 / BASE_WIDTH),
    backgroundColor: '#fff',
    borderRadius: wp(15 / BASE_WIDTH),
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 10, height: 10 },
  },
  commonText: {
    // width: '100%',
    // textAlign: 'center',
    color: '#3D447B',
    fontWeight: 'normal',
    fontSize: hp(32 / BASE_HEIGHT),
    lineHeight: hp(82 / BASE_HEIGHT),
  },
  arrowPic: {
    position: 'absolute',
    top: hp(35 / BASE_HEIGHT),
    right: wp(78 / BASE_WIDTH),
    width: wp(20 / BASE_WIDTH),
    height: hp(12 / BASE_HEIGHT),
    // marginLeft: wp(30 / BASE_WIDTH),
  },
  orderPic: {
    width: wp(48 / BASE_WIDTH),
    height: wp(48 / BASE_WIDTH),
  },
});
